<a href="https://colab.research.google.com/github/Guruvarshini/ML/blob/main/Boston's_housing_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
#separator is one or more spaces
#skip 22 rows as these are comments about dataset
#no header values
df = pd.read_csv("http://lib.stat.cmu.edu/datasets/boston", sep="\s+", skiprows=22, header=None)
print(df)

             0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN 

In [4]:
df.isna().sum()

0       0
1       0
2       0
3     506
4     506
5     506
6     506
7     506
8     506
9     506
10    506
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer
#NaN values to mean
#Imputation strategy (using mean imputation in this example)
imputer = SimpleImputer(strategy='mean')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

#Imputation results
print("\nImputed Data:")
print(df_imputed)


Imputed Data:
             0      1      2        3         4         5          6   \
0       0.00632  18.00   2.31  0.00000  0.538000  6.575000  65.200000   
1     396.90000   4.98  24.00  0.06917  0.554695  6.284634  68.574901   
2       0.02731   0.00   7.07  0.00000  0.469000  6.421000  78.900000   
3     396.90000   9.14  21.60  0.06917  0.554695  6.284634  68.574901   
4       0.02729   0.00   7.07  0.00000  0.469000  7.185000  61.100000   
...         ...    ...    ...      ...       ...       ...        ...   
1007  396.90000   5.64  23.90  0.06917  0.554695  6.284634  68.574901   
1008    0.10959   0.00  11.93  0.00000  0.573000  6.794000  89.300000   
1009  393.45000   6.48  22.00  0.06917  0.554695  6.284634  68.574901   
1010    0.04741   0.00  11.93  0.00000  0.573000  6.030000  80.800000   
1011  396.90000   7.88  11.90  0.06917  0.554695  6.284634  68.574901   

            7         8           9          10  
0     4.090000  1.000000  296.000000  15.300000  
1     3.

In [6]:
x1=df.values[::2,:]
x2=df.values[1::2,:2]
data=np.hstack([x1,x2])
print(data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [7]:
target=df.values[1::2,2]
print(target)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [ ]:
print(df_imputed[0].corr(df_imputed[10]))
print(df_imputed[1].corr(df_imputed[10]))
print(df_imputed[2].corr(df_imputed[10]))
print(df_imputed[3].corr(df_imputed[10]))
print(df_imputed[4].corr(df_imputed[10]))
print(df_imputed[5].corr(df_imputed[10]))
print(df_imputed[6].corr(df_imputed[10]))
print(df_imputed[7].corr(df_imputed[10]))
print(df_imputed[8].corr(df_imputed[10]))
print(df_imputed[9].corr(df_imputed[10]))

0.009369112715897961
-0.3742542069646247
0.1874596046829858
-0.12151517365806241
0.18893267711276698
-0.3555014945590852
0.2615150116719579
-0.2324705424082566
0.4647411785030568
0.4608530350656668


In [8]:
#This process ensures that after standardization, the feature's distribution will have a mean of 0 and a standard deviation of 1.
#((x - μ) / σ)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scal = scaler.fit_transform(data)
print(data_scal)

[[-0.41978194  0.28482986 -1.2879095  ... -1.45900038  0.44105193
  -1.0755623 ]
 [-0.41733926 -0.48772236 -0.59338101 ... -0.30309415  0.44105193
  -0.49243937]
 [-0.41734159 -0.48772236 -0.59338101 ... -0.30309415  0.39642699
  -1.2087274 ]
 ...
 [-0.41344658 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.98304761]
 [-0.40776407 -0.48772236  0.11573841 ...  1.17646583  0.4032249
  -0.86530163]
 [-0.41500016 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.66905833]]


In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_scal, target, test_size=0.2, random_state=42)

In [10]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [11]:
y_pred=model.predict(X_test)

In [ ]:
#The MSE is a measure of the average squared difference between the predicted and actual values. Lower values of MSE indicate better model performance.
#The R-squared score, also known as the coefficient of determination, is a statistical measure that represents the proportion of the variance in the dependent variable (target) that is predictable from the independent variables (features) in a regression model.
from sklearn.metrics import mean_squared_error,r2_score
mse=mean_squared_error(y_pred,y_test)
r2=r2_score(y_pred,y_test)
print(mse,r2)

24.291119474973513 0.6333247469014347


In [25]:
iterations = 0
while r2 < 0.9 and iterations < 50000:
    # Add more iterations as needed
    X_train, X_test, y_train, y_test = train_test_split(data_scal, target, test_size=0.2, random_state=iterations)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    iterations += 1

print("After iterations, R-squared:", r2)


After iterations, R-squared: 0.7506664492035022


In [23]:
user_input = np.array([[ 0.03768  ,80.00  , 1.520 , 0 , 0.4040 , 7.2740 , 38.30 , 7.3090,   2  ,329.0 , 12.60,
  392.20 ,  6.62]])
#actual output=34.60
# Preprocess user inputs
user_input_scal = scaler.transform(user_input)

# Make predictions based on user inputs
predicted_value = model.predict(user_input_scal)

# Display the predicted value
print("Predicted Value:", predicted_value)

Predicted Value: [34.8415505]
